### ISSUE TITLE
Include the list of fonts required for these flyers

### ISSUE THREAD

**Issue by sumnerevans** [ColoradoSchoolOfMines/acm-brand#2]
A list of the fonts required to generate these flyers would be useful.

**Comment by jackrosenthal** [comment]
This is not hard... they are SVG files LOL.

    cat *.svg | sed -Ene "s/.*font-family:([^;]+);.*/\1/p" | sort | uniq

**Comment by jackrosenthal** [comment]
Also put it in a README file...
